### ISSUE TITLE
Contract generation

### ISSUE THREAD

**Issue by freddygv** [Microsoft/ApplicationInsights-Go#14]
Hi,

I'm in the planning phase for developing an exporter from OpenCensus.io's Go library to Azure's AppInsights, and have started by looking through this SDK.

One thing that stood out in my first pass is that there are a lot of auto-generated contracts that do things like enforcing these limits:
https://docs.microsoft.com/en-us/azure/application-insights/app-insights-api-custom-events-metrics#limits

How was the contracts package generated? I will likely need to replicate this functionality.

Thanks!

**Comment by freddygv** [comment]
Maybe the solution is to import the contracts package from this SDK.

**Comment by jjjordanmsft** [comment]
The contracts are generated by an internal tool from the [public endpoint specs](https://github.com/Microsoft/ApplicationInsights-Home/tree/master/EndpointSpecs/Schemas/Bond).  Why the tool is internal is beyond me, but the transformations are generally fairly straightforward.

You could use the `contracts` package directly, although I'm not sure why you wouldn't just use the `appinsights` package so you don't need to reinvent the interface with the data collector, retry, backoff, throttling handling, queueing and so on.

**Comment by freddygv** [comment]
That is a good point, will lean on the `appinsights` package. Thanks for the input.

**Comment by joshgav** [comment]
Hi @freddygv, curious if you've continued to work on this? We're thinking about how to better support OpenCensus in App Insights. Thanks!

cc @devigned @nikmd23

**Comment by nikmd23** [comment]
@freddygv if this is something that is still of interest to you, we'd love your feedback and help as we drive forward.

**Comment by freddygv** [comment]
@joshgav I submitted a proposal for this for the Google Summer of Code but it wasn't accepted, so I never got started on it (and unfortunately cannot make the time to contribute now).

Great to hear that Microsoft joined the project though!
