### ISSUE TITLE
uuid regression issue [multiple-value uuid.NewV4() in single-value context]

### ISSUE THREAD

**Issue by XiaoliangHuang** [Microsoft/ApplicationInsights-Go#20]
# issue
the uuid has regression issue that uuid.NewV4() will return multiple results, but not a single id.  so code like this will faile

```
	// Create operation ID if it does not exist
	if _, ok := envelope.Tags[contracts.OperationId]; !ok {
		envelope.Tags[contracts.OperationId] = uuid.NewV4().String()
	}

```

with error 

```
multiple-value uuid.NewV4() in single-value context
```

similar issue has been reported many times in the uuid official site.

# fix

can use fix like this 

```
client.sessionID = uuid.NewV4().String()
```

```
u,_ := uuid.NewV4()
client.sessionID = u.String()
```

see https://github.com/mlabouardy/dialogflow-go-client/pull/12/commits/951d289fd2b0a745b03635d4718b19ac9e0d1ce9

**Comment by jjjordanmsft** [comment]
I don't think `panic()`'ing on uuid failures is a good idea for this SDK.  However, I will log about them.  Ideally, NewRequestTelemetry might return an `error` but that raises some API consistency issues that I'm not entirely thrilled with.

Somewhat related, I now have satori/go.uuid#73 on my radar, even though committing now won't put us in a worse situation than we were already in.
