### ISSUE TITLE
Wrong version is set in newUUID() call

### ISSUE THREAD

**Issue by tandr** [microsoft/ApplicationInsights-Go#28]
https://github.com/Microsoft/ApplicationInsights-Go/blob/91c278ebf40dacf87986074aed81db50551e0009/appinsights/uuid.go#L55

Instead of `u.SetVersion(uuid.VariantRFC4122)` it should be `u.SetVariant(uuid.VariantRFC4122)` - there is no version `uuid.VariantRFC4122`

**Comment by jjjordanmsft** [comment]
Oof.  Good catch.  Those words are too similar.

**Comment by jjjordanmsft** [comment]
I'd also note that nothing in the pipeline mandates well-formed UUID's.  They just need to be random strings.  So while incorrect, this doesn't really break anything.

**Comment by tandr** [comment]
:) 

I a yet to see a thing that accepts uuid and validates that it is indeed a "valid" uuid...

**Comment by jjjordanmsft** [comment]
This was fixed.
