### ISSUE TITLE
Missing data about operation_parentID

### ISSUE THREAD

**Issue by v-gamaar** [microsoft/ApplicationInsights-Go#29]
Hi Team

We are using this SDK to get telemetry to an application Insights resource, however due to there is not details about how to configure the operation_parentID value we are using the same id in the dependencies tracking, and we are getting an Application Map iterative showing only one instance instead of show the rest of the components interacting with the project. Could you please update this documentation in order to provide more details about the configuration of this vale.

Thanks, have an excellent day.

**Comment by jjjordanmsft** [comment]
Operation ID/Parent Operation ID are left to the user in this SDK.  (The idea behind this is that some autocollection library could be built on top of this to provide those values.)  This can be set on the TelemetryContext object associated with the TelemetryClient or on individual Telemetry instances via:

```go
telemetry.ContextTags()[contracts.OperationParentId] = "parent id"
// or
client.Context().Tags.Operation().SetParentId("parent id")
```

But I guess what you're asking is what these things ought to look like.  I'd point you to [this document](https://docs.microsoft.com/en-us/azure/azure-monitor/app/correlation) to start.  To be fair it's light in details, but should provide a reasonable starting point.

**Comment by SergeyKanzhelev** [comment]
This is a bit outdated article, but it gives an idea what values should be set where to enable Applicaiton Map: http://apmtips.com/blog/2017/10/18/two-types-of-correlation/

**Comment by SergeyKanzhelev** [comment]
Please re-open if you have more questions
