### ISSUE TITLE
Clock dependency is gone

### ISSUE THREAD

**Issue by iamnande** [microsoft/ApplicationInsights-Go#32]
in our `go.mod` we have from a dependency on AppInsights which has a dependency on clock:
```
code.cloudfoundry.org/clock v0.0.0-20180518195852-02e53af36e6c // indirect
```

however, we are currently unable to build projects that depend on AppInsights because of the following error:
```
$ <any go command that does building>
go: code.cloudfoundry.org/clock@v0.0.0-20180518195852-02e53af36e6c: unrecognized import path "code.cloudfoundry.org/clock" (parse https://code.cloudfoundry.org/clock?go-get=1: no go-import meta tags ())
go: error loading module requirements
```

there's also a nice [404 on godoc](https://godoc.org/code.cloudfoundry.org/clock) as well

halp? relates to https://github.com/cloudfoundry/clock/issues/7

**Comment by EmandM** [comment]
Looks like the issue has resolved itself. The godoc is linking correctly to the package again, and go is now resolving the dependency as expected.

**Comment by iamnande** [comment]
@EmandM indeed. closing
