### ISSUE TITLE
Suggestion: Switch to go modules

### ISSUE THREAD

**Issue by HagaiBarel** [microsoft/ApplicationInsights-Go#36]
Hi,
Currently, dependencies are managed using `.gitmodules`. Consider switching to a more standard `go` way of tracking and managing dependencies, such as `go modules` as it seems like the future of `go` packages and dependency management.

Willing to PR it if you'd like.

**Comment by jjjordanmsft** [comment]
This wasn't available when initially implemented, but yes it seems that go 1.11 modules are the way forward.

**Comment by danielnelson** [comment]
I believe that anyone consuming this project using Go modules will not get the vendored go.uuid, either with the associated PR or without, and instead will pull in the go.uuid version with https://github.com/satori/go.uuid/issues/73.

**Comment by jjjordanmsft** [comment]
This was merged.
