### ISSUE TITLE
Suggestion: Enable optional customized http.Client for transmitter

### ISSUE THREAD

**Issue by wmdave** [microsoft/ApplicationInsights-Go#41]
I'm building an application which leverages the app insights go client and, in order to run the resulting application in a minimal container (i.e. one without an OS CA certificate store), I need the ability to programmatically include trusted CA certificates in the transmitter's http.Client.

To enable this, I was thinking of adding the option to include a `*http.Client` option in `TelemetryConfig` which can then be leveraged during `Transmit` to call the app insights endpoint.  If the value of the `TelemetryConfig.Client` option is nil, the call to `newTransmitter` would substitute the `http.DefaultClient` automatically.

**Comment by jjjordanmsft** [comment]
This was merged. Thanks again.
