### ISSUE TITLE
AppInsights reliability

### ISSUE THREAD

**Issue by xackery** [microsoft/ApplicationInsights-Go#48]
Failed to transmit telemetry: Post https://dc.services.visualstudio.com/v2/track: unexpected EOF\n
Failed to transmit telemetry: Post https://dc.services.visualstudio.com/v2/track: write tcp 172.18.0.14:32786->40.71.13.169:443: write: connection timed out\n

This SDK will still send the payloads, but app insights seems to be unreliable, we send tracing data every ~60s and this report will happen and cause our tracing data to go dark for about 30 minutes every other day, across multiple regions. It will recover the missing data once payload is accepted after, but..

Is that an expected level of reliability with AppInsights?

**Comment by jjjordanmsft** [comment]
No, it is not expected, but this is unrelated to the SDK.  There may have been an outage around this time, but I don't recall (and have been away on leave). Please reach out to Azure support in the event that you have this problem in the future.
